### PR TITLE
fix(proto): fix `cargo run-script gen-proto` and regenerate the schema

### LINKED ISSUE #19: proto: bump to buf v2
**[ @SebastianElvis](https://www.github.com/SebastianElvis)** cloned issue [babylonchain/babylon-contract#176](https://www.github.com/babylonchain/babylon-contract/issues/176) on 2024-06-20: 

> https://www.github.com/babylonchain/babylon-contract/pull/158#issuecomment-2178685947

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #19

### CODE REVIEW

**Review by gitferry — APPROVED** [review]

File: scripts/protocgen.sh [hunk 1]
```diff
@@ -1,15 +1,22 @@
...
+# This script generates protobuf messages in Rust using a Buf workspace
+# Use with: `cargo run-script gen-proto` in the root dir.
 
-set -eo pipefail
+set -euo pipefail
 
-cd packages/proto
-# To also initialize, fetch and checkout any nested submodules
+SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
+PROTO_ROOT="$SCRIPT_DIR/packages/proto"
```
Comment (maurolacy) [inline scripts/protocgen.sh:9]:
```suggestion
PROTO_ROOT="$SCRIPT_DIR/../packages/proto"
```

File: scripts/protocgen.sh [hunk 2]
```diff
@@ -1,15 +1,22 @@
...
-# NOTE: use `cargo run-script gen-proto` in the root dir instead.
+# This script generates protobuf messages in Rust using a Buf workspace
+# Use with: `cargo run-script gen-proto` in the root dir.
 
-set -eo pipefail
+set -euo pipefail
 
-cd packages/proto
-# To also initialize, fetch and checkout any nested submodules
+SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
```
Comment (maurolacy) [inline scripts/protocgen.sh:8]:
```suggestion
SCRIPT_DIR=$(dirname "$0")
```
should do.

Comment (liuchengxu) [reply scripts/protocgen.sh:8]: The AI folk does the scripting, as they can do it much better than I can :P. The one in this PR seems to be safer, declared by https://chatgpt.com/s/t_686ef8594f1c8191a1fa559ca0aa5a28.
